trigger: none

pool:
  name: 'Local-Linux'

variables:
  registry: sacdockerzure.azurecr.io
  dockerHubUser: smakavan
  frontendRepo: frontend-app
  backendRepo: backend-app
  tag: $(Build.BuildId)

steps:
# Checkout code
- checkout: self

# ================= MAVEN BUILD =================
- task: Maven@3
  displayName: "Build frontend & backend JARs"
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package -DskipTests'
    
# ================= ACR LOGIN =================

# Login to ACR
#- task: Docker@2
#  displayName: "Login to ACR"
#  inputs:
#    command: login
#    containerRegistry: ACR-Connection

# ================= FRONTEND =================
# Build frontend image
- task: Docker@2
  displayName: "Build frontend image"
  inputs:
    command: build
    containerRegistry: ACR-Connection
    repository: $(frontendRepo)
    dockerfile: frontend/Dockerfile
    buildContext: frontend
    tags: |
      $(tag)

# Push frontend to ACR
#- task: Docker@2
#  displayName: "Push frontend image to ACR"
#  inputs:
#    command: push
#    containerRegistry: ACR-Connection
#    repository: $(frontendRepo)
#    tags: |
#      $(tag)

# Tag frontend for Docker Hub
- script: |
    docker tag $(dockerHubUser)/$(frontendRepo):$(tag)
#    docker tag $(registry)/$(frontendRepo):$(tag) $(dockerHubUser)/$(frontendRepo):$(tag)
  displayName: "Tag frontend for Docker Hub"

# Push frontend to Docker Hub
- task: Docker@2
  displayName: "Push frontend image to Docker Hub"
  inputs:
    command: push
    containerRegistry: DockerHub-Connection
    repository: $(dockerHubUser)/$(frontendRepo)
    tags: |
      $(tag)

# ================= BACKEND =================
# Build backend image
- task: Docker@2
  displayName: "Build backend image"
  inputs:
    command: build
    containerRegistry: ACR-Connection
    repository: $(backendRepo)
    dockerfile: backend/Dockerfile
    buildContext: backend
    tags: |
      $(tag)

# Push backend to ACR
- task: Docker@2
  displayName: "Push backend image to ACR"
  inputs:
    command: push
    containerRegistry: ACR-Connection
    repository: $(backendRepo)
    tags: |
      $(tag)

# Tag backend for Docker Hub
- script: |
    docker tag $(registry)/$(backendRepo):$(tag) $(dockerHubUser)/$(backendRepo):$(tag)
  displayName: "Tag backend for Docker Hub"

# Push backend to Docker Hub
- task: Docker@2
  displayName: "Push backend image to Docker Hub"
  inputs:
    command: push
    containerRegistry: DockerHub-Connection
    repository: $(dockerHubUser)/$(backendRepo)
    tags: |
      $(tag)
