trigger: none

pool:
  name: 'Local-Linux'

variables:
  acrRegistry: sacdockerzure.azurecr.io
  dockerhubRegistry: smakavan
  image_tag: $(Build.BuildId)
  frontend_image: $(acrRegistry)/frontend-app:$(image_tag)
  backend_image: $(acrRegistry)/backend-app:$(image_tag)

steps:

# 1️⃣ Checkout repo
- checkout: self

# 2️⃣ Build Maven JARs (frontend + backend)
- task: Maven@3
  displayName: 'Build frontend and backend JARs'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package -DskipTests'
    
# 3️⃣ Build frontend Docker image
- task: Docker@2
  displayName: 'Build frontend Docker image'
  inputs:
    command: 'build'
    buildContext: 'frontend'
    dockerfile: 'frontend/Dockerfile'
    tags: '$(frontend_image)'

# 4️⃣ Push frontend to ACR
- task: Docker@2
  displayName: 'Push frontend to ACR'
  inputs:
    command: 'push'
    containerRegistry: 'ACR-Connection'       # Azure service connection to ACR
    repository: 'frontend-app'
    tags: '$(image_tag)'

# 5️⃣ Push frontend to Docker Hub
- task: Docker@2
  displayName: 'Push frontend to Docker Hub'
  inputs:
    command: 'push'
    containerRegistry: 'DockerHub-Connection' # Docker Hub service connection
    repository: 'frontend-app'
    tags: '$(image_tag)'

# 6️⃣ Build backend Docker image
- task: Docker@2
  displayName: 'Build backend Docker image'
  inputs:
    command: 'build'
    buildContext: 'backend'
    dockerfile: 'backend/Dockerfile'
    tags: '$(backend_image)'

# 7️⃣ Push backend to ACR
- task: Docker@2
  displayName: 'Push backend to ACR'
  inputs:
    command: 'push'
    containerRegistry: 'ACR-Connection'
    repository: 'backend-app'
    tags: '$(image_tag)'

# 8️⃣ Push backend to Docker Hub
- task: Docker@2
  displayName: 'Push backend to Docker Hub'
  inputs:
    command: 'push'
    containerRegistry: 'DockerHub-Connection'
    repository: 'backend-app'
    tags: '$(image_tag)'
